### ISSUE TITLE
Any new updates?

### ISSUE THREAD

**Issue by playXE** [indutny/linearscan.rs#2]
Hello! Are you planning to update this crate?

**Comment by bnjbvr** [comment]
For what it's worth, I've [forked](https://github.com/bnjbvr/linear_scan) and updated the code to the latest Rust version, to better understand linear scan, and it now passes all the tests again.

**Comment by playXE** [comment]
@bnjbvr oh wow! Very nice! I will try to use your fork in my codegen :)
